[package]
name = "rust-tui-example"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
crossterm = "0.20.0"

[dependencies.tui]
version = "0.16.0"
default-features = false
features = ["crossterm"]
